bigchaindb/bigchaindb-driver

.travis.yml, compose/server/Dockerfile, docker-compose.yml, requirements_dev.txt, setup.py, tests/conftest.py, tests/test_driver.py
~~Will fail as `.travis.yml` i is missing bdb setup, as outlined in #7.~~
=> Integration tests with bdb server

.travis.yml
In case we were being awful citizens of travisland before.
=> Don't run bigchaindb with nohup on travis to make sure it exits after session ends

bigchaindb_driver/driver.py, setup.py, tests/conftest.py, tests/test_driver.py
Fixes #60.
These are some changes that had to be made as the transaction model changed slightly.
@sohkai this is mostly relevant to you at this point.
=> Adjustments due to tx model change

bigchaindb_driver/driver.py
Since the user shouldn't be changing them anyway.
=> Make driver attributes read-only properties

docker-compose.yml
=> Let docker randomly assign a port number

docs/index.rst
As suggested in https://github.com/bigchaindb/bigchaindb/pull/650#discussion_r81301081
=> Add main nav link "← Back to All BigchainDB Docs"

docs/conf.py
* Also removed the `u` in front of some strings. We're using Python 3 so I don't see the point of that.
* Also removed some stuff from the start of `docs/conf.py`
=> Edited docs/conf.py to clarify that these docs are for BigchainDB Python Driver

setup.py
=> Point to bigchaindb 0.7.0.dev

docs/index.rst, setup.py
=> Changed the dev status to Alpha

bigchaindb_driver/driver.py, bigchaindb_driver/exceptions.py, bigchaindb_driver/offchain.py, bigchaindb_driver/utils.py, docs/libref.rst, tests/conftest.py, tests/test_driver.py, tests/test_offchain.py
**IMPORTANT**: targets BigchainDB `0.7.x`
=> Provide separate functions for creating tx payloads, and fulfilling them

bigchaindb_driver/offchain.py, tests/test_offchain.py
=> Support owners_after as a string, and tuple

docs/usage.rst
=> Update basic usage docs

bigchaindb_driver/driver.py, tests/test_driver.py
=> Add deprecation warnings for create() & transfer()

docs/usage.rst
Small example with divisible assets
This was branched from #158. The only file actually changed was `docs/usage.rst`
=> Doc divisible assets

docker-compose.yml, docs/usage.rst
=> Remove unused "api_endpoint" setting

bigchaindb_driver/crypto.py, bigchaindb_driver/driver.py, docs/advanced-usage.rst, docs/handcraft.rst, docs/usage.rst, tests/test_crypto.py
=> Change to public/private key names

bigchaindb_driver/driver.py, docs/libref.rst, tests/conftest.py, tests/test_driver.py
=> Update unspents endpoint to latest changes

bigchaindb_driver/driver.py, bigchaindb_driver/offchain.py, bigchaindb_driver/utils.py, docs/libref.rst, docs/usage.rst
Mostly updates `BigchainDB` class's docstrings to match current behaviour.
Contains some other small typo fixes / adjustments.
=> Additional docstrings changes for 0.9

docs/advanced-usage.rst
Similar to #234.
Note that only https://github.com/bigchaindb/bigchaindb-driver/commit/0ce630daf23bfddc453ee04d31655fc19d6a5d38, https://github.com/bigchaindb/bigchaindb-driver/commit/1675ae588051a0296c6568d27facbe8fd8b854ee, and https://github.com/bigchaindb/bigchaindb-driver/commit/88df45c7859665dbbe58ddf1615eafe1d0ffde5b contain non-whitespace changes.
**Note**: I've avoided changing the sections with todo (e.g. hashlocks, thresholds, timelocks, etc) aside from modifying any direct access to a transaction that had become obsolete (see https://github.com/bigchaindb/bigchaindb-driver/commit/88df45c7859665dbbe58ddf1615eafe1d0ffde5b).
--------
=> Update advanced usage docs for 0.9

docs/advanced-usage.rst, docs/handcraft.rst, docs/usage.rst
Similar to #234 and #235.
No preview because it's too big 😢
=> Update handcrafting usage docs for 0.9

bigchaindb_driver/connection.py, bigchaindb_driver/driver.py, bigchaindb_driver/exceptions.py, tests/conftest.py, tests/test_driver.py
=> 214 get tx list

bigchaindb_driver/driver.py, tests/test_driver.py
=> Update the inner mechanics of .status()

docs/advanced-usage.rst, docs/connect.rst, docs/index.rst, docs/usage.rst
This resolves #152 
I also changed the way that H1, H2 and H3 headings are created in `advanced-usage.rst`, to be consistent with the other pages.
=> New docs page w/ examples of how to connect

docs/aboutthedocs.rst, docs/usage.rst
- Added a working/complete code example on asset creation and transfer in docs
=> Include code example

bigchaindb_driver/driver.py, bigchaindb_driver/utils.py, tests/test_driver.py, tests/test_utils.py
=> Add node normalization function

bigchaindb_driver/driver.py
=> Replace old endpoint "unspents" with new "outputs"

docs/handcraft.rst, tests/conftest.py, tests/test_driver.py
This pr adds support for cryptoconditions draft 02 spec.
- Updated fixtures
- Fixed tests
- Updated handcrafting transactions
=> Cryptoconditions 02 support

.ci/travis-before-script.sh, bigchaindb_driver/driver.py, docs/libref.rst, docs/usage.rst, tests/conftest.py, tests/test_driver.py, tox.ini
resolves #292 
- Added support for the assets endpoint
- Added tests
- Added documentation
=> Added support for text search endpoint

docs/handcraft.rst
=> Update handcrafting transactions

docs/usage.rst
I'll create a new issue to solve the problem itself and propose ideas to automate the indentation/styling of rst
=> indent ipython blocks, fixes #334

docs/advanced-usage.rst
forgot to ref the issue D: 
#332
=> document m-of-m multiple owners for CREATE

.ci/travis-install.sh, compose/driver/Dockerfile, compose/server/Dockerfile, setup.py, tests/conftest.py, tests/test_offchain.py, tox.ini
Make necessary modifications to work with upcoming change brought by https://github.com/bigchaindb/bigchaindb/pull/1899
=> Fulfill and hash

docs/advanced-usage.rst, docs/handcraft.rst, docs/usage.rst
Updating the docs according to the changes in #343 
also based on #343 
None
#343
None
None
None
List general components of the application that this PR will affect:
- Docs
=> Update docs fulfill and hash

.github/ISSUE_TEMPLATE.md
I've added the BigchainDB version to the issue template. This can help spotting some incompatibilities fast.
=> Add BigchainDB server version

docs/handcraft.rst, docs/usage.rst, tests/conftest.py, tests/test_driver.py, tests/test_offchain.py
Solution: update documentation and tests
Fixes #353
None
None
None
None
None
=> Problem: 'unique messages for fulfillments' is not included in driver

README.rst, bigchaindb_driver/driver.py, docs/advanced-usage.rst, docs/handcraft.rst, docs/usage.rst, tests/test_driver.py
Solution: remove the transaction status and update documentation
Fixes #361 
bigchaindb/bigchaindb#1946
=> Problem: the transaction status is deprecated

bigchaindb_driver/offchain.py, docs/handcraft.rst, docs/usage.rst, tests/conftest.py
Solution: update version from 1.0 to 2.0
Tests for this PR should fail. We have to wait for a new test environment that runs with BigchainDB 2.0.
But I guess this can still be reviewed.
Fixes #355 
https://github.com/bigchaindb/bigchaindb/pull/2048
=> Problem: The tx version is not updated

tests/test_driver.py
Solution: remove skip marks for the database backend
Fixes #376
=> Problem: tests are skipped because of the database backend

bigchaindb_driver/driver.py, docs/advanced-usage.rst, tests/test_driver.py
Solution: Migtrate blocks api to return one block id or None
Refer  #366
=> Problem: Transaction cannot be present in multiple blocks

tests/conftest.py, tests/test_driver.py
Solution: Fix necessary tests for release.
=> Problem: Driver tests failing

Makefile, docker-compose.yml
Solution: update the Makefile and make it easy to use
Fixes #384
=> Problem: the Makefile is outdated

CODE_OF_CONDUCT.md
Solution: Add a code of conduct
Fixes #391
=> Problem: There is no set of rules for behaviour for the contributors

tests/test_driver.py
Solution: skip tests with non unique transactions
=> Problem: tests are failing

tests/test_driver.py
=> Problem: pdb comment in test

CONTRIBUTING.rst
Solution: add C4, COSS and BEPs to the documentation
Fixes #395
=> Problem: Contributors don't know about C4, COSS and BEP

README.rst
Solution: hint how to install a pre-release
Fixes #396
=> Problem: pip installs the latest stable release and not the pre-release

setup.py
Solution: set python version for pypi
Fixes #350
=> Problem: no specific python version for pip

setup.py
=> Problem: setup.py does not include submodules

docs/quickstart.rst
Solution: Add instructions to install alpha, beta or RC versions
=> Problem: No instructions to install alpha version

docs/advanced-usage.rst, docs/usage.rst
Solution: explain how to check for the status of a tx in the docs
related to #419
=> Problem: It is not known how to check the status of a transaction

Makefile
Solution: add new commands and remove old ones
=> Problem: .PHONY of Makefile is not up to date

CONTRIBUTING.rst, Makefile, docs/connect.rst
Solution: add useful Makefile commands to the docs
Fixes #425
=> Problem: the updated Makefile is not mentioned in the docs

README.rst
Solution: update the README and add an usage example
removed some links that are not used anymore
added a TOC
added a user example
removed pyup badge
added some helpful links
=> Problem: The README is not userfriendly enough

README.rst, docs/index.rst, docs/readme.rst
Solution: remove readme from docs and change path of image
=> Problem: image not shown on GitHub

README.rst
Solution: use the correct tx id with transfer step
Fixes #449
=>  Problem: the demo script in README does not work 

.ci/travis-after-success.sh, .ci/travis_script.sh, .gitignore
Solution: add upload path for codecov file
=> Problem: codecov setup not simple enough

README.rst, docs/quickstart.rst
Solution: Add some notes about the OS support.
=> Problem: Docs do not mention supported OSes.

bigchaindb_driver/common/exceptions.py
Solutions: remove leftover exceptions
=> Problem: bdb voting does not exist anymore

docker-compose.yml
Solution: upgrade to new versions used in BigchainDB
=> Problem: we use old versions of tendermint and mongodb

bigchaindb_driver/connection.py
Solution: Cap exponential backoff depending on the timeout value allowing for more aggresive trying and reasonable waiting time in the event of a network recovery.
Solves #469.
=> Problem: Unlimited backoffs are inconvenient.

tests/test_driver.py
Solution: rewrite test without fixtures
I couldn't find the underlying problem with the fixtures. In general we had difficulties in the past. Fixtures being reused and the tests being not independent led to errors and failing tests. It would be nice to find the reason why they are failing but worst case I waste a lot of time on it and I'm already out of ideas how to debug it.
I tried to make the test as short as possible, if you see any lines I can shorten, please tell me.
=> Problem: the tests are failing

docs/conf.py, docs/requirements.txt, setup.py
Analogue of bigchaindb/bigchaindb#2537
I also made `docs/requirements.txt` consistent with `setup.py`
=> Fix assorted Sphinx problems.

setup.py
=> Update minimum version of requests package
