bigchaindb_driver/driver.py
tests/test_driver.py

Adds a small test for retrieving statuses of unfound transactions and fixes up documentation for the function.

Small fixes for status endpoint

---

bigchaindb_driver/exceptions.py
docs/libref.rst

Reverts commit 9c4f5fa77f27349cb141fbd1578c331ab6bd91d0.
As @sbellem [points out](https://github.com/bigchaindb/bigchaindb-driver/pull/64#issuecomment-246295605), this can be confusing when using multiple
drivers and having a fully named exception is common practice.

Revert "Rename BigchaindbException to DriverException"

---

bigchaindb_driver/driver.py
tests/test_driver.py

Some small sanity checks for making sure the keys are strings and that if a signing key is given, a verifying key is also given.
Not sure if it'll ever be useful to only give a signing key, but I imagine the other way around (only binding a verifying key to the driver) may be useful for people to only supply their signing key when absolutely necessary.

Add sanity checks to given keypairs during driver initialization

---

CONTRIBUTING.rst
compose/server/Dockerfile
dependency_links.txt

Otherwise we'll have to remember to change the dependency each time we need to work on upstream API changes from BigchainDB.
On the fence about this though; maybe we should be pegging the BigchainDB versions we test against on release as specific driver versions are made to work for specific versions of  BigchainDB?

Keep test dependencies on BigchainDB's master branch

---

README.rst

I did a grep for the old ReadTheDocs URL and updated all instances (all of which were in `README.rst`):
* in the ReadTheDocs badge
* in the link to the docs

Updated ReadTheDocs URLs

---

docs/installation.rst
travis_pypi_setup.py

On Gitter, @gabrielmendanha noted that some of the links to the bigchaindb/bigchaindb-driver repo were broken in the page about Installation. Correct links have the form:
...github.com/bigchaindb/bigchaindb-driver...
but in the page about Installation, they had the form:
...github.com/bigchaindb/bigchaindb_driver...
with an underscore instead of a dash. I changed the underscore `_` to a dash `-`.
@sbellem I'm not as sure about the change I made in `travis_pypi_setup.py`. Can you take a look?

Fixed links to bigchaindb/bigchaindb-driver repo on GitHub

---

README.rst
docs/installation.rst

* Moved all the installation-related docs to the **Installation** page.
* Expanded the **Installation** page by documenting how to install all the prerequisites (OS-level, Python 3, and pip).

Moved all installation-related docs to that page and expanded it

---

bigchaindb_driver/driver.py
bigchaindb_driver/offchain.py

The exact error was:
'ERROR: Unknown interpreted text role "exception".'

Fix docstrings error

---

bigchaindb_driver/driver.py
docker-compose.yml
tests/test_driver.py

Oops, turns out we didn't actually use the default node.

Properly set default connection node if none given

---

bigchaindb_driver/driver.py
bigchaindb_driver/offchain.py
bigchaindb_driver/utils.py
tests/test_offchain.py

Reverts bigchaindb/bigchaindb-driver#168
Overlooked multi key dict case, e.g.:
```python
owners_after=[([carly.verifying_key], 5), ([carly.verifying_key], 5)]
```

Revert "Refine flexible support for owners_after"

---

HACKING.rst
MANIFEST.in
docs/index.rst
docs/quickstart.rst

Due to the current dependency on bigchaindb server code, when the master branch is needed installing with pip requires using the flag `--process-dependency-links`, which may be unknown to many users. The added docs aim to provide the possibly missing information.

Add hacking file and doc section

---

README.rst

Arguments for removing it:
- We don't have tests confirming the compatibility for every change that lands
in master of both bigchaindb/bigchaindb and bigchaindb/bigchaindb-driver
- It involves a lot of effort to check whether or not master and master are
compatible
- We shouldn't check manually (if we want to have this mapping, lets
automate it)
- There has already been a case where users got confused:
https://gitter.im/bigchaindb/bigchaindb?at=5846b0abf666c5a138d91959

Remove master:master mapping in compatibility matrix

---

docs/advanced-usage.rst
docs/handcraft.rst
docs/index.rst
docs/usage.rst

**Note to reviewers**:
* The plan of this PR is to provide a rough cut of working examples that have almost no dependence on the driver itself.
* The examples are meant to be compatible with the latest PyPI release, 0.1.2.
* Once merged, the plan is to make a maintenance release (0.1.3) for which these new docs will be available.
Subsequent work will be part of 0.2.0 such that the driver will be brought up to speed with the latest server code.
As for the examples, work will be done to remove all dependencies on the driver, such that they can be shown under the server docs,

Add handcrafting transaction docs rough cut

---

bigchaindb_driver/__init__.py
setup.cfg
setup.py

Reverts bigchaindb/bigchaindb-driver#191 -- docs are broken

Revert "Bump version: 0.1.2 → 0.1.3"

---

bigchaindb_driver/driver.py
bigchaindb_driver/offchain.py
bigchaindb_driver/utils.py
docs/conf.py
tests/conftest.py
tests/test_driver.py
tests/test_offchain.py

Fixes #221.
Interface changes from upstream:
* `owners_before` argument was renamed to `tx_signers` (renamed to `signers` for the driver interface)
* `owners_after` argument was renamed to `recipients`
* `Fulfilment` class was renamed to `Input`
* `conditions` in transaction was renamed to `output`
* `fulfillments` in transaction was renamed to `input`
bigchaindb/bigchaindb#1089 details a bug found that causes two tests to fail.

Fix driver interfaces for tx model changes in 0.9

---

bigchaindb_driver/offchain.py
tests/test_offchain.py

`prepare_create_transaction` should strip out the `data` from the provided `asset` to pass into `Transaction.create()`.

Fix `prepare_create_transaction` leaving `data` in asset

---

docs/usage.rst

In general I've tried to make the language consistent with what the server uses (e.g. "outputs" instead of "conditions").
Note that only https://github.com/bigchaindb/bigchaindb-driver/pull/234/commits/9343ebea186555520e5f5f74334542abd3547faf and https://github.com/bigchaindb/bigchaindb-driver/pull/234/commits/cb83a9d4c9e17e2d37d8eb4c5a861535da2a2b95 contain non-whitespace changes.
-----------

Update basic usage docs for 0.9

---

docs/handcraft.rst

Transaction model's version must be a string

---

docs/usage.rst

The docs now better-account for the fact that there's a small time delay before a transaction is in a valid block (and hence considered valid).
This resolves #209
This resolves #174

Docs: Put try/except in loop to check if tx is valid

---

docs/advanced-usage.rst

Missed this earlier.
Fixes #131.

Remove dangling instance of signing key in docs

---

docs/usage.rst

I do think we still need this bit... see https://github.com/bigchaindb/bigchaindb-driver/pull/251/files#r99296405.
Fixes some extraneous whitespace and tabs as well. Only commit that has non-cosmetic changes is 534961e.

Add back `bdb` instance into basic usage examples

---

docs/usage.rst

Oops, must've missed this earlier.

Fix token transfer example in basic usage docs

---

.ci/travis-before-script.sh
HACKING.rst
bigchaindb_driver/driver.py
compose/server/Dockerfile
docker-compose.yml
docs/advanced-usage.rst
docs/connect.rst
docs/handcraft.rst
docs/usage.rst
pytest.ini
setup.py
tests/conftest.py
tests/test_driver.py

Add support for:
* `GET /`
* `GET /api/{version}`
via the `BigchainDB` class, which now only requires the scheme, hostname and port (e.g.: http://localhost:9984')

Get info of a node and its api root

---

docs/advanced-usage.rst
docs/connect.rst
docs/quickstart.rst
docs/usage.rst

Trent made some comments about the Python Driver docs this morning. I think these changes might help. For example, now there is no "Step 2" without a "Step 1" before it.
I also streamlined some of the language and presentation, to make it easier to follow.

docs simplifications/clarifications

---

docs/index.rst
setup.py

In `setup.py`, I changed the classifier `'Development Status :: 3 - Alpha'` to `'Development Status :: 4 - Beta'` as per the list of classifiers here: https://pypi.python.org/pypi?%3Aaction=list_classifiers
I also removed the "Important" notice about "Development Status: Alpha" from the Index page.
This is in preparation for the version 1.0 release (of BigchainDB Server) but I think it's probably fine to have it in master now.

Update from alpha to beta

---

.ci/travis-install.sh
bigchaindb_driver/driver.py
bigchaindb_driver/offchain.py
docs/advanced-usage.rst
docs/handcraft.rst
docs/usage.rst
setup.py
tests/conftest.py
tests/test_driver.py
tests/test_offchain.py
tox.ini

resolves #291 
This updates the driver to support the breaking changes introduced in the HTTP API to be released with version 1.0 of BigchainDB.
This was tested against BigchainDB master branch with all the breaking changes https://github.com/bigchaindb/bigchaindb/commit/571ee83731d9ed5a80aae65ab612bae52a354f98
The BigchainDB dependency of the bigchaindb-driver is also using the same code.
- Update info endpoints
- Amount is now a string
- Output endpoint:
- `unspent` -> `spent`
- ability to only return spent outputs
- Rename of `txid` and `tx_id` to `transaction_id`
- Data models
- http arguments
- Updated the documentation
- Rename all occurrences of `txid` to `transaction_id`, again!

Support HTTP API v1.0

---

CONTRIBUTING.rst
compose/driver/Dockerfile
compose/server/Dockerfile
docker-compose.yml

This PR updates the docker-compose file so that:
1. MongoDB can be used as a backend when running BigchainDB server.
2. The websocket events API can be used.
Note for @ttmc this will most likely require minor changes to docs. Will add you as a reviewer once the docs have been updated.

Docker files updates

---

tests/test_driver.py

Changed the skip condition for the assets tests.
It now checks what is the backend being used in the bigchaindb config instead of the environment variable. This way we can run the tests without having to set the environment variable. Useful when testing locally.

Fix skip of assets tests

---

docs/handcraft.rst
docs/quickstart.rst

- Fixes quickstart for a fresh Ubuntu/RHEL setup,
and installs all the relevant dependencies.

Fix quickstart guide for bigchaindb_driver

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.rst

Recently while updating test net k8s cluster a recently added API endpoint
was skipped from testing because DevOps team was not aware of the new
endpoint and an issue with this endpoint on new cluster was only caught after
we moved the test net to new cluster. To avoid this in the future this PR adds a 
standard PR template to delegate dependencies whenever applicable.
**READY**
Repo/Branch | PR
------ | ------
bigchaindb/bigchaindb | [link](https://github.com/bigchaindb/bigchaindb/pull/1776)
No impact on deployment
Create a new PR and the template should be visible
- No Scale impact
- No Performance impact
- No Security impact
- Documentation impact: Developer documentation needs to be updated

Add standard template for creating PRs

---

docs/advanced-usage.rst
docs/handcraft.rst
docs/usage.rst

changes:
- added some recaps to have a nice summarization every now and then
- in some cases, I moved the key generation up to the beginning. Now this step has to be done just once and different examples (e.g. revision vs handcrafted) have always the same keys and are independent of each other
- at some points, one step was breaking the flow of another step e.g. having a danger box in the middle of an explanation and the actual code; an example: https://github.com/bigchaindb/bigchaindb-driver/compare/331-make-examples-self-contained?expand=1#diff-97e179b8c1a3dd00093a5e8707257a90L405
- I removed `from bigchaindb_driver.crypto import CryptoKeypair` when we were not just showing a recap. If someone wants to copy/paste a code block we can't assume that the keys are already there
- I also …

make examples self-contained, fixes #331

---

docs/quickstart.rst

* Adding python development library and headers as a dependency for
cryptography.
* Also reference to official cryptography installation guide.
* Restructure document

Minor changes in the quickstart guide for installation of bdb-driver

---

.ci/travis-after-success.sh
.ci/travis-before-install.sh
.ci/travis-before-script.sh
.ci/travis-install.sh
.ci/travis_script.sh
.travis.yml
tox.ini

- Updated `docker-compose.yml`
- Remove `docker-compose.rdb.yml` because RethinkDB is not supported with BigchainDB v2.0
- Update Travis configuration to test with `localmongodb` and BigchainDB v2.0 instead of BigchainDB <=1.3.0 and `rethinkdb`.
- Consolidate all deployment methods in a single `docker-compose` file i.e. `docs.yml` should move into `docker-compose.yml` as well.
- Remove `dev.yml` because it is deprecated(RethinkDB is not supported with 2.0)
Fixes #368 
:fire::fire::fire: Travis will fail with this PR but we will have dependent changes that will take care of those tests @codegeschrei  can confirm :fire::fire::fire:

Problem: Dev environment is outdated and no integration with Tendermint

---

bigchaindb_driver/driver.py
docs/handcraft.rst
tests/test_driver.py

Solution: add and document mode parameter for transactions
For now I guessed the changes for the tests, I still need to test them with a new dev environment.
Fixes #359 
bigchaindb/bigchaindb#1951

Problem: transaction query parameter mode is not implemented

---

tests/test_driver.py

Solutions: remove the public key from tests
Fixes #374

Problem: public key is currently not exposed in BigchainDB Server

---

bigchaindb_driver/driver.py

Solution: remove status parameter and adjust documentation
FYI: I thought we had this in our documentation, but I couldn't find anything.
#360 
bigchaindb/bigchaindb#2021

Problem: the status parameter for querying a block is deprecated

---

setup.py

Solution: update the current version to 2.0.0.dev
Fixes #370 
https://github.com/bigchaindb/bigchaindb/pull/2150

Problem: current BigchainDB Server version is outdated in setup.py

---

docker-compose.yml

Solution: change the docker file to driver and remove unused arguments
Fixes #372

Problem: building docs with docker-compose uses the docker server file

---

bigchaindb_driver/driver.py
docs/advanced-usage.rst
tests/test_driver.py

Solution: change parameter to block_height and update documentation
Fixes #362 
bigchaindb/bigchaindb#1970

Problem: block_id parameter for block query is now block_height

---

tests/conftest.py
tests/test_driver.py

Solution: use unique transaction

Problem: Transactions were used twice in tests

---

Makefile

Solution: remove container to run tests
We already have a command to run tests, so they should not be run with `make start`

Problem: make start should only start server containers

---

LICENSE
README.rst

Solution: add a LICENSE for the repository
We have a `LICENSES` file with two licenses which is not recognised by GitHub.

Problem: no license shown in Github

---

bigchaindb_driver/common/__init__.py
bigchaindb_driver/common/crypto.py
bigchaindb_driver/common/exceptions.py
bigchaindb_driver/common/transaction.py
bigchaindb_driver/common/utils.py
bigchaindb_driver/offchain.py
setup.py
tests/conftest.py

Solution: copy the module `common` in the source of the driver, and update dependencies.
Copy code is not the ideal solution, but we need to unlock https://github.com/bigchaindb/bigchaindb/pull/2235.
Moreover, we have a [path forward](https://github.com/bigchaindb/BEPs/pull/33).

Problem: the driver depends on BigchainDB package

---

Makefile
docker-compose.yml

Solution: upgrade tendermint to match the version the server uses
The server recently upgraded to a newer tendermint version and these changes were not yet reflected in the driver. They also led to problems when using docker.

Problem: the driver is using an old tendermint version

---

README.rst

Solution: reference BigchainDB setup

Problem: The Quickstart doc does not link to BDB setup

---

README.rst

This brings the installation instructions in `README.rst` to be similar to the installation instructions in the Python Driver docs. Mostly, it adds help with installing pre-release versions.

In README.rst, add help w/ installing pre-release versions

---

docs/usage.rst

Actually if using the example, a ``CREATE`` transaction is consumed, and its ID is used.
Fixes #436

Documentation fix

---

bigchaindb_driver/driver.py
tests/test_driver.py

Solution: remove keyrings from tests and docs

Problem: info endpoint does not return keyrings

---

docs/conf.py

Solution: auto update copyright year
inspired by @ttmc PR at bigchaindb https://github.com/bigchaindb/bigchaindb/pull/2353

Problem: wrong copyright year in docs

---

.coveragerc
codecov.yml

Solution: remove it from codecov
The `common` package is checked in codecov but the tests were not included when it was copied from `bigchaindb`. Since there will be a new solution for `common` soon, the tests will not be copied and  it'll just be ignored by codecov.

Problem: common code is not tested

---

bigchaindb_driver/common/exceptions.py

Solution: remove KeypairNotFoundException
The exception was removed in the [bigchaindb repository](https://github.com/bigchaindb/bigchaindb/commit/2b39566a4b93fe6a95356b2d350326ff049ce825#diff-c03138cb428bd41d7c7bf527924b3d5c)

Problem: KeypairNotFoundException does not exist anymore

---

bigchaindb_driver/connection.py
bigchaindb_driver/driver.py
bigchaindb_driver/exceptions.py
bigchaindb_driver/pool.py
bigchaindb_driver/transport.py
bigchaindb_driver/utils.py
docs/advanced-usage.rst
tests/conftest.py
tests/test_driver.py
tests/test_pool.py
tests/test_transport.py
tests/test_utils.py

Solution: Improve the implementation:
- remove busy wait;
- only retry connection errors;
- simplify the code;
- make custom headers overwrite common headers, not vice versa;
- add some more tests;
- remove obsolete await_transaction;
- make the linter pass.

Problem: The round robin strategy has issues.

---

LICENSES.md

The docs license was CC-BY-SA-4. This change was in preparation for the HL application.

Change docs license to CC-BY-4

---

bigchaindb_driver/common/transaction.py
setup.py

cyrptoconditions dependency updated because of vulnerability CVE-2018-10903
See https://github.com/bigchaindb/cryptoconditions/issues/105 and https://github.com/bigchaindb/cryptoconditions/issues/107

Problem: cyrptoconditions dependency updated because of vulnerability

---

docs/handcraft.rst

The docs would build, but the generated "Handcrafting Transactions" page was full of valid Python errors of the form:
`TypeError: Object of type 'bytes' is not JSON serializable`
I guess sometimes people _want_ to show the actual error messages in their docs, so such errors don't prevent Sphinx from thinking everything is okay.
Solution: Use `base58.b58encode(key).decode()` which is a str, instead of `base58.b58encode(key)` which is a bytes object. I defined a little helper function named `b58()` to reduce verbosity.
I don't know if this will get ReadTheDocs to start working (as per issue #475), but it does remove all the "Traceback" messages in the "Handcrafting Transactions" page of the docs.

Problem: Error when building Handcrafting Transactions docs

---

setup.py

This is to get ReadTheDocs working, or at least partly working. To understand the reasoning, see https://github.com/bigchaindb/bigchaindb/pull/2512

Pin cryptoconditions==0.7.2 in setup.py, for now

---

bigchaindb_driver/driver.py
tests/test_driver.py

Solution: remove the send function
Fixes #482

Problem: The send function is deprecated

---

docs/handcraft.rst
docs/quickstart.rst

It seems you can no longer define a function using IPython inside docs. That used to work. It stopped working, and it seems that's what caused the 'Handcrafting Transactions' page to stop building lately.
I also updated and simplified the 'Quickstart' page in the docs.

Fixed 'Handcrafting Transactions' & 'Quickstart' docs

---

setup.py

to be consistent with bigchaindb

Let python-rapidjson~=0.6.0

---

compose/bigchaindb_driver/Dockerfile
docs/advanced-installation.rst
tox.ini

The `--process-dependency-links` option is no longer supported by `pip` as of version 19.0. See https://pip.pypa.io/en/stable/news/#id4

Remove --process-dependency-links everywhere
